### PR TITLE
fix: replace tech spec v. 2.0.1 with v. 2.0.0

### PR DESCRIPTION
**Pull request by raimundo-henriques**
@helloanil, 
@levi-ratnakar and @kelly-fleming,
@mill6-plat6aux,

cc @prasadt1 

Hello! We are submitting this PR for your review. This PR corrects the Pathfinder Technical Spec Version for Conformance of your solution and test Results. There was a miscommunication from our side, the version of Pathfinder Tech Spec is actually v 2.0.0 and not v 2.0.1 since v 2.0.1 is still in draft. Hope this is ok for you and we can go ahead and get this PR approved from you so we can merge it. 

Thanks for your review and apologies for the confusion.

### CODE REVIEW

**Comment by levi-ratnakar** [comment]
@raimundo-henriques Sounds good to me.

**Comment by raimundo-henriques** [comment]
Thank you @levi-ratnakar !

**Comment by raimundo-henriques** [comment]
Thank you @helloanil !

**Comment by mill6-plat6aux** [comment]
I believe each company's implementation was version `2.0.1-20230314`, is this a problem?

Also, should we cross-test again after the 2.0.1 release?

**Comment by prasadt1** [comment]
> I believe each company's implementation was version `2.0.1-20230314`, is this a problem?
> 
> Also, should we cross-test again after the 2.0.1 release?

@mill6-plat6aux  - Thanks for your comments. V 2.0.1 only contains minor changes to fix typos etc. and nothing changed in terms of the HTTP Rest API standards that you tested conformance for in V 2.0.0. So you are not required to do a conformance for V 2.0.1 again. But I would also recommend if you still want to participate in a future connectathon and test for V 2.0.1 as well. In that case your solution will also listed as Conformant to V 2.0.1 as well alongwith V 2.0.1. Again - this is not mandatory and completely voluntary.

**Comment by mill6-plat6aux** [comment]
@prasadt1 Understood. Thank you for your response.

**Pull request merged**
