### PR TITLE
Merge pull request #66 from wbcsd/test-typo

### PR DESCRIPTION
**Pull request by JohnDevitt**

### CODE REVIEW

**Review by raimundo-henriques — APPROVED** [review]

**Comment by raimundo-henriques** [comment]
@JohnDevitt,
I took the liberty of committing directly on your branch to fix what seemed to be a typo: Altruistiq's solution in the catalog has version `2.0.0`, rather than `1.0.0`.
Can you please confirm if you agree with this change?
Thank you,
Best,

**Comment by JohnDevitt** [comment]
> @JohnDevitt, I took the liberty of committing directly on your branch to fix what seemed to be a typo: Altruistiq's solution in the catalog has version `2.0.0`, rather than `1.0.0`. Can you please confirm if you agree with this change? Thank you, Best,
> 
> cc. @prasadt1

We've implemented v2 at co2ai and we tested Altrusitiq for v2 also. Both of these should be v2 IMO.

**Comment by raimundo-henriques** [comment]
@JohnDevitt , do you mean the version of the technical specifications? That one is identified in the `"pathfinder_version"` field and it's indeed `2.0.1`.

My change concerned the version of Altruistiq's solution. Each solution (`"tested_solution"` and `"tested_by"`, that is) includes a `"version"` field that identifies the version of the solution. Altruistiq's solution in the catalog is identified as version `2.0.0` (as indicated in their solution name), but the value of the `"version"` field was `1.0.0`, hence my change. 

Thank you!

**Comment by JohnDevitt** [comment]
> @JohnDevitt , do you mean the version of the technical specifications? That one is identified in the `"pathfinder_version"` field and it's indeed `2.0.1`.
> 
> My change concerned the version of Altruistiq's solution. Each solution (`"tested_solution"` and `"tested_by"`, that is) includes a `"version"` field that identifies the version of the solution. Altruistiq's solution in the catalog is identified as version `2.0.0` (as indicated in their solution name), but the value of the `"version"` field was `1.0.0`, hence my change.
> 
> Thank you!

Apologies, right you are.

We're also v1, so I've added another PR to fix that. We're all good to go now I believe :)

**Comment by raimundo-henriques** [comment]
I'm glad we could clarify it! Thank you for your quick responses! 
We will merge your PR right away

**Pull request merged**
