### PR TITLE
add cirrusnexustruecarbonforpact01 solution from Cirrus Nexus

### PR DESCRIPTION
**Pull request by levi-ratnakar**

### CODE REVIEW

**Comment by kelly-fleming** [comment]
Hi,

Levi Ratnakar has made this submission on behalf of Cirrus Nexus.  Please advise if we should make any changes.

Thanks!

**Comment by prasadt1** [comment]
@levi-ratnakar @kelly-fleming - thanks for submitting this PR, we are in process of reviewing it and will merge it soon if no issues, otheriwse will reply via comments in the PR. cc: @raimundo-henriques

**Comment by raimundo-henriques** [comment]
Hello @levi-ratnakar and @kelly-fleming,

Thanks for onboarding your solution!

It conforms to our syntactic requirements, but I would ask you to consider using the id `cirrus-nexus-true-carbon-for-pact-01` instead, just for ease of readability. Would that be ok with you?

Also, in order to make sure that all information about the company is correctly displayed as it should, we would like to ask you for some more details about the company. The goal is to make sure that your brand is correctly represented, both in the solution's detail page and in the collaborators section. All we need is another small json (in `/catalog/users/cirrus-nexus.json`), that I took the liberty to pre-fill:
``` json
{
  "id": "cirrus-nexus",
  "kind": "solutionprovider",
  "name": "Cirrus Nexus",
  "email": "info@cirrus-nexus.com",
  "website": "https://www.cirrus-nexus.com/",
  "logo": ""
}
```
If you agree, we would ask you to double check all the information and please provide a url for your logo, to display it in the collaborators page.

Thank you, 
best,

**Comment by kelly-fleming** [comment]
Hi,

Thanks for reaching out.  We will make the updates per your request and get an update to the PR in by tomorrow.

Regards,

Kelly Fleming
Chief Information Officer
***@***.***<https://www.cirrus-nexus.com/>





One World Trade Center
85th Floor
New York, NY 10007

T:  +1 929 251 7122
M: +1 201 953 0647
E: ***@***.******@***.***>
www.cirrus-nexus.com<https://www.cirrus-nexus.com/>

***@***.***<https://www.linkedin.com/in/kelly-fleming-83a81031/>

**Comment by levi-ratnakar** [comment]
@raimundo-henriques We have done required changes in solutions and users. Please let us know if there is anything we need to change.

cc: @kelly-fleming

**Comment by raimundo-henriques** [comment]
@levi-ratnakar Thank you for the update!

I'm afraid I still need to ask you for three small changes:

(1) The solution's directory must be the solution's id. Hence, in this case, either the path becomes `catalog/solutions/cirrus-nexus-true-carbon-for-pact-01/2.0.0/solution.json` or we leave the path as is and change the solution id to `"truecarbon"`. (I realize now that I could have pointed this out yesterday and apologize for that.)

(2) The version and name fields in the `solution.json` need to be swapped. (i.e.:
```json
{
  "id": "",
  "version": "",
  "name": "",
  ...
}
```
)

(3) The name of the `json` in the `users` directory must be the provider's id. In this case, rather than `truecarbon.json`, it should be `cirrus-nexus.json`.

Thank you for your cooperation! 

cc @kelly-fleming

**Comment by levi-ratnakar** [comment]
@raimundo-henriques Thanks a lot for suggesting the changes. We have made the requested changes for the naming convention and updated the PR. Please have a look and feel free to suggest if there is anything else we might need to change.

cc: @kelly-fleming

**Pull request merged**
